### PR TITLE
add original event as an additional callback parameter

### PR DESCRIPTION
**Pull request by heliocorreia**

### CODE REVIEW

**Comment by heliocorreia** [comment]
@rbiggs, do you intend to publish a npm package any time soon?

**Comment by rbiggs** [comment]
This is an npm package. You install it through the namespace:
```bash
npm install -D @composi/gestures
```
Or am I missing something here?

**Comment by rbiggs** [comment]
Since its in a namespace, on npm you would have to look for `@composi/gestures`.

**Comment by rbiggs** [comment]
By the way, if you're using `@composi/core` and create a new project, `@composi/gestures` gets installed automatically. You just need to import it into your new project.
You create new Composi projects with `@composi/create-composi-app`.

**Comment by heliocorreia** [comment]
The last (2 months ago) published version at `https://www.npmjs.com/package/@composi/gestures` is `1.0.4`. This version does not have this PR.

**Comment by rbiggs** [comment]
Oops! My bad. I forget to bump the version after accepting your pull request 🤭. Just published this now as version 1.0.5.

**Comment by rbiggs** [comment]
@composi/create-composi-app is also updated to include the latest version of @composi/gestures as well.

**Pull request merged**
